//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.WSQImageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSQImageService.IWSQImageService")]
    public interface IWSQImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSQImageService/SaveWSQImage", ReplyAction="http://tempuri.org/IWSQImageService/SaveWSQImageResponse")]
        void SaveWSQImage(int id, byte[] buffer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSQImageServiceChannel : WindowsService.WSQImageService.IWSQImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSQImageServiceClient : System.ServiceModel.ClientBase<WindowsService.WSQImageService.IWSQImageService>, WindowsService.WSQImageService.IWSQImageService {
        
        public WSQImageServiceClient() {
        }
        
        public WSQImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSQImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSQImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSQImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveWSQImage(int id, byte[] buffer) {
            base.Channel.SaveWSQImage(id, buffer);
        }
    }
}
