//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonService.WSQImageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSQImageService.IWSQImageService")]
    public interface IWSQImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSQImageService/SaveWSQImage", ReplyAction="http://tempuri.org/IWSQImageService/SaveWSQImageResponse")]
        void SaveWSQImage(int id, byte[] buffer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSQImageService/DeserializeWSQArray", ReplyAction="http://tempuri.org/IWSQImageService/DeserializeWSQArrayResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ArrayList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[][]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fingersCollection")]
        System.Collections.ArrayList DeserializeWSQArray(byte[] serializedWSQArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSQImageService/processEnrolledData", ReplyAction="http://tempuri.org/IWSQImageService/processEnrolledDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ArrayList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[][]))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fingersCollection")]
        System.Collections.ArrayList processEnrolledData(byte[][] serializedWSQArray);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSQImageServiceChannel : CommonService.WSQImageService.IWSQImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSQImageServiceClient : System.ServiceModel.ClientBase<CommonService.WSQImageService.IWSQImageService>, CommonService.WSQImageService.IWSQImageService {
        
        public WSQImageServiceClient() {
        }
        
        public WSQImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSQImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSQImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSQImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveWSQImage(int id, byte[] buffer) {
            base.Channel.SaveWSQImage(id, buffer);
        }
        
        public System.Collections.ArrayList DeserializeWSQArray(byte[] serializedWSQArray) {
            return base.Channel.DeserializeWSQArray(serializedWSQArray);
        }
        
        public System.Collections.ArrayList processEnrolledData(byte[][] serializedWSQArray) {
            return base.Channel.processEnrolledData(serializedWSQArray);
        }
    }
}
