//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService.DatabaseService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMAGE_TYPE", Namespace="http://schemas.datacontract.org/2004/07/DataService")]
    public enum IMAGE_TYPE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        picture = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        wsq = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseService.IDbDataService")]
    public interface IDbDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbDataService/GetImage", ReplyAction="http://tempuri.org/IDbDataService/GetImageResponse")]
        byte[] GetImage(WindowsService.DatabaseService.IMAGE_TYPE imageType, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbDataService/SendImage", ReplyAction="http://tempuri.org/IDbDataService/SendImageResponse")]
        void SendImage(WindowsService.DatabaseService.IMAGE_TYPE imageType, int id, ref byte[] buffer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbDataServiceChannel : WindowsService.DatabaseService.IDbDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbDataServiceClient : System.ServiceModel.ClientBase<WindowsService.DatabaseService.IDbDataService>, WindowsService.DatabaseService.IDbDataService {
        
        public DbDataServiceClient() {
        }
        
        public DbDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetImage(WindowsService.DatabaseService.IMAGE_TYPE imageType, int id) {
            return base.Channel.GetImage(imageType, id);
        }
        
        public void SendImage(WindowsService.DatabaseService.IMAGE_TYPE imageType, int id, ref byte[] buffer) {
            base.Channel.SendImage(imageType, id, ref buffer);
        }
    }
}
