//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.ConfigurationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationService.IConfigurationService")]
    public interface IConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/AppSettings", ReplyAction="http://tempuri.org/IConfigurationService/AppSettingsResponse")]
        System.Collections.Generic.Dictionary<string, string> AppSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/ConnectionStrings", ReplyAction="http://tempuri.org/IConfigurationService/ConnectionStringsResponse")]
        System.Collections.Generic.Dictionary<string, string> ConnectionStrings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/getAppSetting", ReplyAction="http://tempuri.org/IConfigurationService/getAppSettingResponse")]
        string getAppSetting(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/getConnectionString", ReplyAction="http://tempuri.org/IConfigurationService/getConnectionStringResponse")]
        string getConnectionString(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationServiceChannel : DAO.ConfigurationService.IConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<DAO.ConfigurationService.IConfigurationService>, DAO.ConfigurationService.IConfigurationService {
        
        public ConfigurationServiceClient() {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> AppSettings() {
            return base.Channel.AppSettings();
        }
        
        public System.Collections.Generic.Dictionary<string, string> ConnectionStrings() {
            return base.Channel.ConnectionStrings();
        }
        
        public string getAppSetting(string key) {
            return base.Channel.getAppSetting(key);
        }
        
        public string getConnectionString(string name) {
            return base.Channel.getConnectionString(name);
        }
    }
}
